# Generated by Django 3.2.3 on 2021-11-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='email',
            field=models.EmailField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='password',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='tipo_usuario',
            field=models.CharField(default='Autor', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user'),
        ),
    ]
