# Generated by Django 3.2.3 on 2021-11-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211124_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.TextField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'archivos',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('palabras_clave', models.CharField(max_length=255)),
                ('resumen', models.TextField()),
                ('topico', models.CharField(max_length=255)),
                ('autor', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
    ]
