# Generated by Django 3.2.3 on 2021-11-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evaluadores_asignados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluadores_asignados',
            old_name='proyecto_id',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='evaluadores_asignados',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
