# Generated by Django 3.2.3 on 2021-12-13 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cuentas_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluadores_asignados',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.evaluacion'),
        ),
    ]
