# Generated by Django 3.2.3 on 2021-11-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211128_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluadores_asignados',
            name='valor_evaluacion',
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_reporte', models.DateTimeField()),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.archivos')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.proyectos')),
                ('usuario_reporteador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cuentas')),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
        migrations.AddField(
            model_name='evaluadores_asignados',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.evaluacion'),
        ),
    ]
