# Generated by Django 3.2.3 on 2021-11-25 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_archivos_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
