# Generated by Django 3.2.3 on 2021-11-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proyectos_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
