# Generated by Django 3.2.3 on 2021-11-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211128_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='usuario_reporteador',
        ),
    ]
