# Generated by Django 3.2.3 on 2021-11-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_proyectos_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='estado',
            field=models.IntegerField(default=2),
        ),
    ]
