# Generated by Django 3.2.3 on 2021-11-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_proyectos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.user'),
        ),
    ]
