# Generated by Django 3.2.3 on 2021-11-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211128_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.archivos'),
        ),
    ]
